name: Synchronize

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0/15 * * * *'

jobs:
  sync:
    name: "Synchronize"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: Angelk90/actions-download-file@master
        id: downloadfile
        name: Download a master.db from expugn
        with:
          url: '["https://raw.githubusercontent.com/Expugn/priconne-database/master/master_jp.db"]'
          target: ./

      - name: Generate .csv dump
        run: |
          . .github/scripts/dump.sh master_jp.db

      - name: Commit, create PR, and merge
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          VERSION="$(jq .truth_version version)"
          git config user.name "sehnauoi"
          git config user.email "sehnauoi@users.noreply.github.com"

          git add *
          git commit -m "Update"
          git push -u origin "patch/$VERSION"
          gh pr create --title "Update $VERSION" --body "Created automatically w/ github actions"
          gh pr merge --merge -d
