name: Synchronize

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '00 00 * * *'

jobs:
  sync:
    name: "Synchronize"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: Angelk90/actions-download-file@master
        id: download1
        name: Download a master.db from expugn
        with:
          url: '["https://raw.githubusercontent.com/Expugn/priconne-database/master/master_jp.db"]'
          target: ./
          
      - uses: Angelk90/actions-download-file@master
        id: download2
        name: Download a file
        with:
          url: '["https://raw.githubusercontent.com/sehnauoi/c/main/a.py", "https://raw.githubusercontent.com/Expugn/priconne-quest-helper/master/data/character_data.json"]'
          target: ./

      - name: Run Python
        run: |
          pip install pandas
          python a.py

      - name: Generate .csv dump
        run: |
          . .github/scripts/dump.sh master_jp.db

      - name: Check files
        run: ls

      - name: Commit, create PR, and merge
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          git config user.name "sehnauoi"
          git config user.email "sehnauoi@users.noreply.github.com"

          git add *.csv
          git commit -m "Update"
          git push
