name: Synchronize

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0/15 * * * *'

jobs:
  sync:
    name: "Synchronize"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if we have new version
        id: new_version
        run: |
          DIFF="$(git diff -p -1 version)"
          if [[ "$DIFF" = "" ]]; then
            echo "There is no new version!"
            exit 0
          fi
          echo "::set-output name=exists::true"
          
      - uses: Angelk90/actions-download-file@master
        if: steps.new_version.outputs.exists == 'true'
        id: downloadfile
        name: Download a file
        with:
          url: '["https://raw.githubusercontent.com/Expugn/priconne-database/master/master_jp.db"]'
          target: public/images

      - name: Generate .csv dump
        if: steps.new_version.outputs.exists == 'true'
        run: |
          . .github/scripts/dump.sh master_jp.db

      - name: Commit, create PR, and merge
        if: steps.new_version.outputs.exists == 'true'
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          VERSION="$(jq .truth_version version)"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add *.csv version
          git checkout -b "patch/$VERSION"
          git commit -m "$VERSION"
          git push -u origin "patch/$VERSION"
          gh pr create --title "Update $VERSION" --body "Created automatically w/ github actions"
          gh pr merge --merge -d
