name: Synchronize

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0/15 * * * *'

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone supercharge website repository
      uses: actions/checkout@v2

    # This part here is cloning a second repository
    # While cloning the repository:
    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`
    - name: Clone redive_jp
      uses: actions/checkout@v2
      with:
        repository: HerDataSam/redive_jp_db_diff
        path: resources/docs/2.x
        ref: 2.x

    - name: Commit, create PR, and merge
      if: steps.new_version.outputs.exists == 'true'
      run: |
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        VERSION="$(jq .truth_version version)"
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git checkout -b "patch/$VERSION"
        git commit -m "$VERSION"
        git push -u origin "patch/$VERSION"
        gh pr create --title "Update $VERSION" --body "Created automatically w/ github actions"
        gh pr merge --merge -d
