name: Synchronize

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0/15 * * * *'

jobs:
  sync:
    name: "Synchronize"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Expose Runner Virtual Environment Image Version
        run: echo "ImageVersion=$ImageVersion" >> $GITHUB_ENV

      - name: cloning
        run: |
          git clone https://github.com/HerDataSam/redive_jp_db_diff

      - name: Check if we have new version
        id: new_version
        run: |
          DIFF="$(git diff -p -1 version)"
          if [[ "$DIFF" = "" ]]; then
            echo "There is no new version!"
            exit 0
          fi
          echo "::set-output name=exists::true"

      - name: Generate .csv dump
        if: steps.new_version.outputs.exists == 'true'
        run: |
          . .github/scripts/dump.sh master.db

      - name: Commit, create PR, and merge
        if: steps.new_version.outputs.exists == 'true'
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          VERSION="$(jq .truth_version version)"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add *.csv version
          git checkout -b "patch/$VERSION"
          git commit -m "$VERSION"
          git push -u origin "patch/$VERSION"
          gh pr create --title "Update $VERSION" --body "Created automatically w/ github actions"
          gh pr merge --merge -d
